# Generated by Django 3.1.2 on 2020-11-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.DecimalField(decimal_places=2, max_digits=15)),
                ('email', models.EmailField(max_length=254)),
                ('menssagem', models.TextField(max_length=255)),
            ],
        ),
    ]
